export const routes = {
  home: "/",
  auth: "/auth",
  signIn: "/auth",
  signUp: "/auth/sign-up",
  verifyOTP: "/auth/verify-otp",
  resetPassword: "/auth/reset-password",
  forgotPassword: "/auth/forgot-password",
  dashboard: "/dashboard/smart-pc",
  storage: "/dashboard/storage",
  callback: "/auth/callback",
  smartStorage: "/smart-storage",
  buildPc: "/build-smartpc",
  pcViewer: "/pc-viewer",
  changePassword: "/auth/change-password",
  users: "/dashboard/users",
  billing: "/dashboard/billing",
  support: "/dashboard/support",
  tutorials: "/dashboard/tutorials",
  profileSecurity: "/dashboard/profile?tab=security",
};

export const publicRoutes: string[] = [
  routes.home,
  routes.signIn,
  routes.signUp,
  routes.forgotPassword,
  routes.resetPassword,
  routes.verifyOTP,
  routes.callback,
  routes.buildPc,
  routes.changePassword,
  "/login",
  "/index",
  "/shared-folder-viewer",
  "/auth/mfa-totp",
  "/auth/mfa-email",
  "/auth/mfa-select",
  "/unsubscribe",
  "/about",
  "/contact",
  "/privacy",
  "/terms",
  "/auth/forgot-password/mfa",
  "/auth/password-required",
];
