import type { Tutorial } from "@/types/tutorial";

export const tutorials: Tutorial[] = [
  {
    id: 1,
    title: "Introduce Sense PC",
    duration: "0:56",
    description:
      "Build a powerful cloud PC in minutes and access it from any browser, on any device, from anywhere - no hardware needed.",
    videoUrl: "https://dj27q01b9pdam.cloudfront.net/SENSEPC%201.mp4",
    youtubeUrl: "https://youtube.com",
    thumbnail: "/assets/images/gettingStartedWithSensePc.png",
    category: "Basic",
    difficulty: "Beginner",
    uploadDate: "2025-12-25",
    lastUpdated: "2025-12-25",
    showCategory: true,
  },
  {
    id: 2,
    title: "How Sense PC Works",
    duration: "1:30",
    description:
      "See how SensePC delivers fast performance with built-in security - plus user management, billing, support ticketing, and in-app tutorials after login.",
    videoUrl: "https://dj27q01b9pdam.cloudfront.net/SENSEPC%203.mp4",
    youtubeUrl: "https://youtube.com/watch?v=performance",
    thumbnail: "/assets/images/optimizing.jpg",
    category: "Sense PC Overview",
    difficulty: "Beginner",
    uploadDate: "2025-12-25",
    lastUpdated: "2025-12-25",
    showCategory: true,
  },
  {
    id: 3,
    title: "Introduce Sense Cloud",
    duration: "0:50",
    description:
      "Securely store, organize, preview, and share files with smart cloud storage that stays synced across all your devices.",
    videoUrl: "https://dj27q01b9pdam.cloudfront.net/SENSEPC%202.mp4",
    youtubeUrl: "https://youtube.com/watch?v=storage",
    thumbnail: "/assets/images/storageManagement.png",
    category: "Storage",
    difficulty: "Beginner",
    uploadDate: "2025-12-25",
    lastUpdated: "2025-12-25",
    showCategory: true,
  },
  {
    id: 4,
    title: "Create and Use Your Sense PC",
    duration: "2:15",
    description:
      "Learn how to create your Sense PC, connect to it, and use the core features to get started fast.",
    videoUrl: "https://dj27q01b9pdam.cloudfront.net/SENSEPC%204.mp4",
    youtubeUrl: "https://youtube.com/watch?v=create-use",
    thumbnail: "/assets/tutorials/video-4.png",
    category: "Getting Started",
    difficulty: "Beginner",
    uploadDate: "2026-01-26",
    lastUpdated: "2026-01-26",
    showCategory: true,
  },
  {
    id: 5,
    title: "Sense PC Features Overview",
    duration: "2:22",
    description:
      "Explore the core Sense PC features and how they help you work faster and more securely.",
    videoUrl: "https://dj27q01b9pdam.cloudfront.net/SENSEPC%205.mp4",
    youtubeUrl: "https://youtube.com/watch?v=features",
    thumbnail: "/assets/tutorials/video-5.png",
    category: "Overview",
    difficulty: "Intermediate",
    uploadDate: "2026-01-26",
    lastUpdated: "2026-01-26",
    showCategory: true,
  },
  {
    id: 6,
    title: "Sense Cloud Use and Features",
    duration: "1:37",
    description:
      "Learn how to use Sense Cloud and explore its key features for storage and sharing.",
    videoUrl: "https://dj27q01b9pdam.cloudfront.net/SENSEPC%206.mp4",
    youtubeUrl: "https://youtube.com/watch?v=sense-cloud",
    thumbnail: "/assets/tutorials/video-6.png",
    category: "Sense Cloud",
    difficulty: "Beginner",
    uploadDate: "2026-01-26",
    lastUpdated: "2026-01-26",
    showCategory: true,
  },
  {
    id: 7,
    title: "User Management Overview",
    duration: "1:32",
    description:
      "See how user management works and how to control access across your team.",
    videoUrl: "https://dj27q01b9pdam.cloudfront.net/SENSEPC%207.mp4",
    youtubeUrl: "https://youtube.com/watch?v=user-management",
    thumbnail: "/assets/tutorials/video-7.png",
    category: "Management",
    difficulty: "Intermediate",
    uploadDate: "2026-01-26",
    lastUpdated: "2026-01-26",
    showCategory: true,
  },
];
