@profile-and-security @regression
Feature: Update Profile and Security Settings
  As a user
  I want to be able to Update my Profile or Security Setting

  Background: I want to be able to sign up to the application and then login with new credentials
    Given I am on the homepage
    When I click the Sign in link
    Then I should be on the login page
    When I click the Sign up link
    Then I should be on the sign up page
    When I enter all the details
    And I click the sign up button
    Then I should be signed up successfully
    And I should be on verify email page
    When I enter OTP
    And I click the verify OTP button
    Then I should be able to verify email successfully
    And I should be on the login page
    When I setup API interception for login
    And I enter newly created email and password
    And I click the login button
    Then I should be logged in successfully
    And I capture the access token from login
    And I should see the dashboard

  @enable-disable-mfa-through-authenticator-app
  Scenario: Enable/Disable Security MFA
    Given I am on the Security and Privacy page
    When I click on Setup for Authenticator App
    Then I should see Setup Authenticator App popup
    When I setup authenticator app through API
    And I enter 6 digit OTP code
    And I Click on Confirm button
    Then I should be able to verify Disable button is displayed
    When I click on header user account icon
    And I click on Logout button
    Then I should be logged out successfully
    And I should be on the login page
    When I click the Sign in link
    Then I should be on the login page
    When I enter newly created email and password
    And I click the login button
    And I enter 6 digit MFA code generated by authenticator app
    Then I should see the dashboard
    When I click on Security and Privacy link
    Then I should be on the Security and Privacy page
    When I click on disable button
    Then I should be able to see Setup for Authenticator App button

  @enable-disable-mfa-through-email-otp
  Scenario: Enable/Disable MFA through Email OTP
    Given I am on the Security and Privacy page
    When I click on Setup for Email Authentication OTP
    Then I should be able to verify Disable button is displayed
    When I click on header user account icon
    And I click on Logout button
    Then I should be logged out successfully
    And I should be on the login page
    When I click the Sign in link
    Then I should be on the login page
    When I enter newly created email and password
    And I click the login button
    And I enter OTP generated by email
    And I Click on Verify Code button
    Then I should see the dashboard
    When I click on Security and Privacy link
    Then I should be on the Security and Privacy page
    When I click on disable button
    Then I should be able to see Setup for Email Authentication OTP button

  @change-password
  Scenario: Change Password
    Given I am on the Security and Privacy page
    When I change password with new password
    Then I should be able to see Change Password Successfully message
    When I click on header user account icon
    And I click on Logout button
    Then I should be logged out successfully
    And I should be on the login page
    When I click the Sign in link
    Then I should be on the login page
    When I enter newly created email and new password
    And I click the login button
    Then I should be logged in successfully
    And I should see the dashboard

  @profile-settings
  Scenario: Profile Settings
    Given I am on the Profile Information page
    Then I should be able to verify full name
    And I should be able to verify email
    When I enter new full name
    And I enter country
    And I click on Save Changes button
    Then I should be able to see Profile Updated Successfully message
    And I should be able to verify updated full name
    And I should be able to verify updated country
    